# Generated by Django 5.1 on 2025-01-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LayerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('filedata', models.FileField(upload_to='layer_files/')),
            ],
        ),
        migrations.CreateModel(
            name='LEDSpectrumData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('filedata', models.FileField(upload_to='led_spectrum_files/')),
            ],
        ),
        migrations.CreateModel(
            name='MultilayerFilmData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('filedata', models.FileField(upload_to='multilayer_files/')),
            ],
        ),
    ]
