# Generated by Django 5.1 on 2025-01-28 01:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FourierOptics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=7)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('aperture_type', models.CharField(max_length=100)),
                ('wavelengths', models.JSONField()),
                ('intensities', models.JSONField()),
                ('number_of_slits', models.IntegerField()),
                ('distance_between_slits', models.FloatField()),
                ('slit_width', models.FloatField()),
                ('slit_height', models.FloatField()),
                ('aperture_radius', models.FloatField()),
                ('add_lens', models.BooleanField()),
                ('distance_lens_to_aperture', models.FloatField()),
                ('focal_length', models.FloatField()),
                ('distance_screen_to_aperture', models.FloatField()),
                ('screen_width', models.FloatField()),
                ('screen_height', models.FloatField()),
                ('resolution', models.IntegerField()),
                ('animation_frames', models.IntegerField()),
                ('animation_framerate', models.IntegerField()),
                ('anim_heatmap_plot_data', models.JSONField()),
                ('anim_3d_plot_data', models.JSONField()),
                ('anim_lines_plot_data', models.JSONField()),
                ('anim_rgb_plot_data', models.JSONField()),
                ('rgb_animation_path', models.CharField(blank=True, max_length=255, null=True)),
                ('intensity_animation_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourieroptics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
