# Generated by Django 5.1 on 2025-01-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourieroptics',
            name='intensity_animation_path',
            field=models.FileField(blank=True, null=True, upload_to='animations/'),
        ),
        migrations.AlterField(
            model_name='fourieroptics',
            name='rgb_animation_path',
            field=models.FileField(blank=True, null=True, upload_to='animations/'),
        ),
    ]
