# Generated by Django 5.1.5 on 2025-01-30 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_fourieroptics_animation_framerate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fourieroptics',
            old_name='intensities',
            new_name='lightsource',
        ),
        migrations.RemoveField(
            model_name='fourieroptics',
            name='screen_height',
        ),
        migrations.RemoveField(
            model_name='fourieroptics',
            name='wavelengths',
        ),
    ]
