# Generated by Django 5.1.5 on 2025-01-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_intensities_fourieroptics_lightsource_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fourieroptics',
            old_name='lightsource',
            new_name='intensities',
        ),
        migrations.AddField(
            model_name='fourieroptics',
            name='wavelengths',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
