# Generated by Django 5.1 on 2025-01-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourieroptics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='intensity_animation_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='rgb_animation_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
