# Generated by Django 5.1 on 2025-01-28 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fourieroptics', '0002_simulationresult_intensity_animation_path_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimulationResult',
        ),
    ]
